version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
networks:
  default:
    external:
      name: elastic